DROP TABLE IF EXISTS students;
DROP TABLE IF EXISTS enrollments;

CREATE TABLE students (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    first_name varchar(25),
    last_name varchar(50),
    nationality varchar(100),
    height_in_cm numeric,
    birthday date
);

INSERT INTO students (id, first_name, last_name, nationality, height_in_cm, birthday)
VALUES (1, 'Malcolm', 'Kee', 'Malaysia', 172, '1990-10-13'),
    (2, 'John', 'Doe', 'Canada', 175, '1989-12-12'),
    (3, 'John', 'Wick', 'United State', 180, '1980-03-12'),
    (4, 'Siti', 'Nurhaliza', 'Malaysia', 165, '1985-03-23'),
    (5, 'David', 'Licauco', 'Philippines', 180, '1995-06-15'),
    (6, 'JJ', 'Lin', 'Singapore', 172, '1981-03-27'),
    (7, 'Juancho', 'Trivino', 'Philippines', 182, '1993-04-13');

CREATE TABLE enrollments (
	id integer GENERATED BY DEFAULT AS IDENTITY,
	student_id integer,
    course_id varchar(25),
	semester varchar(25),
	credit_hour integer,
    enrolled_date date
);

SELECT * FROM enrollments;

INSERT INTO enrollments (student_id, course_id, semester, credit_hour, enrolled_date)
VALUES (1, 'JS001', '2021-01', 2, '2021-01-04'),
    (2, 'JS001', '2021-01', 2, '2021-01-04'),
    (3, 'JS001', '2021-01', 2, '2021-01-04'),
    (5, 'JS001', '2021-01', 2, '2021-01-04'),
    (6, 'JS001', '2021-01', 2, '2021-01-04'),
    (7, 'JS001', '2021-01', 2, '2021-01-04'),
    (1, 'CS050', '2021-01', 3, '2021-01-04'),
    (3, 'CS050', '2021-01', 3, '2021-01-04'),
    (6, 'CS050', '2021-01', 3, '2021-01-04'),
    (1, 'HT001', '2020-02', 2, '2020-06-01'),
    (2, 'HT001', '2020-02', 2, '2020-06-01'),
    (7, 'HT001', '2020-02', 2, '2020-06-01'),
    (5, 'HT001', '2020-02', 2, '2020-06-01'),
    (5, 'DB001', '2021-01', 2, '2021-01-04'),
    (3, 'DB001', '2021-01', 2, '2021-01-04'),
    (1, 'VS001', '2021-01', 1, '2021-01-04'),
    (1, 'VS001', '2021-01', 1, '2021-01-04');