CREATE TABLE movies (
	id bigserial,
	title text,
	language text
);

INSERT INTO movies (title, language)
VALUES ('Sing 2', 'EN'),
	('Ghostbusters: Afterlife', 'EN'),
	('Spider-Man: No Way Home', 'EN'),
	('Encanto', 'EN'),
	('Resident Evil: Welcome to Raccoon City', 'EN'),
	('Eternals', 'EN'),
	('The Matrix Resurrections', 'EN'),
	('Venom: Let There Be Carnage', 'EN'),
	('Red Notice', 'EN'),
	('Shang-Chi and the Legend of the Ten Rings', 'EN'),
	('Survive the Game', 'EN'),
	('Fortress', 'EN'),
	('劇場版「鬼滅の刃」無限列車編', 'JA'),
	('Hotel Transylvania: Transformania', 'EN'),
	('Clifford the Big Red Dog', 'EN'),
	('Harry Potter 20th Anniversary: Return to Hogwarts', 'EN'),
	('劇場版 七つの大罪 光に呪われし者たち', 'JA'),
	('The Amazing Spider-Man', 'EN'),
	('Ida Red', 'EN'),
	('Sooryavanshi', 'HI'),
	('Spider-Man: Homecoming', 'EN'),
	('Encounter', 'EN'),
	('Son', 'EN'),
	('Antlers', 'EN'),
	('Dangerous', 'EN'),
	('The Last Duel', 'EN'),
	('The Amazing Spider-Man 2', 'EN'),
	('Spider-Man: Far From Home', 'EN'),
	('Wild Indian', 'EN'),
	('Diary of a Wimpy Kid', 'EN'),
	('Back to the Outback', 'EN'),
	('Dos', 'ES'),
	('Gone Mom: The Disappearance of Jennifer Dulos', 'EN'),
	('Free Guy', 'EN'),
	('No Time to Die', 'EN'),
	('Dune', 'EN'),
	('Hilda and the Mountain King', 'EN');

